FROM quay.vapo.va.gov/vapo/va/python/python-312
WORKDIR /opt/app-root/src
RUN yum install -y python3-pip && \
    yum clean all -y
COPY . .
RUN pip install --no-cache-dir -r requirements.txt
CMD ["python3", "./app.py"]